# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2024.01.24
_src_path: gh:scientific-python/cookie
backend: hatch
email: rkansal@cern.ch
full_name: Raghav Kansal
license: MIT
org: rkansal47
project_name: HHbbVV
project_short_description: HHbbVV
url: https://github.com/rkansal47/HHbbVV
vcs: false
